# <center> Pandas

- Pandas kütüphanesi veri analizi için kullanılan bir kütüphanedir.
- Panel Data'dan ismi gelmektedir.
- Yapısal veriler ile çalışmak için kullanılır.
- Veri manüplasyonu ve analizi için yazılmış açık kaynak kodlu bir Python kütüphanesidir.
- Ekonometrik ve finansal verilerle çalışmak için kullanılır.
- 2008 yılında Wes McKinney tarafından geliştirilmiştir.

- **Kurulum:**
- `pip install pandas`

## Pandas Serisi oluşturma

`pd.Series()` ile pandas serisi oluşturabiliriz.

In [2]:
import pandas as pd
import numpy as np
seri = pd.Series([1,2,3,4,5,6,7,8,9])
print(seri)

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64

In [2]:
type(seri)

pandas.core.series.Series

`.axes` ile serinin başlangıç, bitiş ve adım değerlerini görebiliriz.

In [3]:
print(seri.axes)

[RangeIndex(start=0, stop=9, step=1)]

`.dtype` ile serinin veri tipini görebiliriz

In [5]:
print(seri.dtype)

int64

`.size` serinin boyutunu gösterir

In [6]:
print(seri.size)

9

`.ndim` serinin boyut sayısını gösterir

In [7]:
print(seri.ndim)

1

`.values` ile serinin değerlerini görebiliriz.

In [8]:
print(seri.values)

[1 2 3 4 5 6 7 8 9]

`.head()` ile ilk 5 değer, .head(x) ile ilk x değer gösterir. Örn.: .head(3) ilk 3 gösterilir.

In [9]:
print(seri.head())

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [10]:
print(seri.head(3))

0    1
1    2
2    3
dtype: int64

`.tail()` ile son 5 değer ve parantez içine yazılan kadar son değerleri döndürür.

In [12]:
print(seri.tail())

4    5
5    6
6    7
7    8
8    9
dtype: int64

## Index İsimlendirmesi

In [16]:
seri1 = pd.Series([99,22,332,94,5], index = ["a","b","c","d","e"])

In [17]:
print(seri1["a"])

99

In [18]:
print(seri1["a" : "c"])

a     99
b     22
c    332
dtype: int64

In [19]:
sozluk = {"reg" : 10, "log" : 11, "cart" : 12}
print(sozluk)
seri = pd.Series(sozluk)
print("---")
print(seri)

{'reg': 10, 'log': 11, 'cart': 12}
---
reg     10
log     11
cart    12
dtype: int64

In [20]:
randomNumbers = np.random.randint(10,100,5)
pandas = pd.Series(randomNumbers)
print(pandas[0])

17

In [21]:
seri = pd.Series([200,121,150,99], index = ["a","b","c","d"])
print(seri)

a    200
b    121
c    150
d     99
dtype: int64

In [22]:
seri.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [24]:
seri.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [25]:
seri.keys

<bound method Series.keys of a    200
b    121
c    150
d     99
dtype: int64>

In [27]:
type(seri)

pandas.core.series.Series

In [26]:
print(list(seri.items()))

[('a', 200), ('b', 121), ('c', 150), ('d', 99)]

In [28]:
"a" in seri

True

In [29]:
"z" in seri

False

In [30]:
seri[["a","b"]]

a    200
b    121
dtype: int64

In [31]:
print(seri)
seri["a"] = 250
print("---")
print(seri)

a    200
b    121
c    150
d     99
dtype: int64
---
a    250
b    121
c    150
d     99
dtype: int64

## Pandas ile DataFrame oluşturma

### pd.DataFrame()

- DataFrame oluşturabilirsiniz
- columns parametresi ile sütun isimlerini belirleyebiliriz
- index parametresi ile index isimlerini belirleyebiliriz

In [6]:
l = [1,2,3,4,5]
pd.DataFrame(l, columns= ["first column"])

   first column
0             1
1             2
2             3
3             4
4             5

In [8]:
m = np.arange(1,10).reshape((3,3))
pd.DataFrame(m, columns=["a","b","c"])

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [14]:
df = pd.DataFrame(m, columns=["var1","var2","var3"])
df.head(2)

   var1  var2  var3
0     1     2     3
1     4     5     6

In [15]:
df.columns = {"degisken1", "degisken2", "degisken3"}
df

   degisken3  degisken2  degisken1
0          1          2          3
1          4          5          6
2          7          8          9

In [17]:
df.axes

[RangeIndex(start=0, stop=3, step=1),
 Index(['degisken3', 'degisken2', 'degisken1'], dtype='object')]

In [18]:
df.shape

(3, 3)

In [19]:
df.ndim

2

In [20]:
df.size

9

In [21]:
df.values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
df.tail(1)

   degisken3  degisken2  degisken1
2          7          8          9

## Eleman işlemleri

In [25]:
s1 = np.random.randint(10, size = 5)
s2 = np.random.randint(10, size = 5)
s3 = np.random.randint(10, size = 5)

In [32]:
sozluk = {"var1" : s1, "var2" : s2, "var3" : s3}
df = pd.DataFrame(sozluk)
df

   var1  var2  var3
0     8     7     9
1     3     5     4
2     2     7     1
3     8     7     3
4     0     8     1

In [33]:
df[0 : 1]

   var1  var2  var3
0     8     7     9

In [34]:
df.index = ["a","b","c","d","e"]
df

   var1  var2  var3
a     8     7     9
b     3     5     4
c     2     7     1
d     8     7     3
e     0     8     1

In [35]:
df[0 : 1]

   var1  var2  var3
a     8     7     9

In [36]:
df["c" : "e"]

   var1  var2  var3
c     2     7     1
d     8     7     3
e     0     8     1

### df.drop()
- .drop() ile kolon veya satır silme işlemi yapabiliriz
- axis = 1 ile kolon silme işlemi yapabiliriz
- axis = 0 ile satır silme işlemi yapabiliriz

In [37]:
df.drop("a",axis = 0)

   var1  var2  var3
b     3     5     4
c     2     7     1
d     8     7     3
e     0     8     1

In [39]:
df

   var1  var2  var3
a     8     7     9
b     3     5     4
c     2     7     1
d     8     7     3
e     0     8     1

### inplace = True
parametresi ile değişikliği kalıcı kaydetme işlemi yapabiliriz. Diğer durumlarda değişiklikler kalıcı olarak kaydedilir.

In [40]:
df.drop("a", axis = 0, inplace = True)
df

   var1  var2  var3
b     3     5     4
c     2     7     1
d     8     7     3
e     0     8     1

In [41]:
df

   var1  var2  var3
b     3     5     4
c     2     7     1
d     8     7     3
e     0     8     1

In [42]:
l = ["var1","var2","var3"]
for i in l:
    print(i in l)

True
True
True

In [43]:
df["var4"] = df["var1"] / df["var2"]
df

   var1  var2  var3      var4
b     3     5     4  0.600000
c     2     7     1  0.285714
d     8     7     3  1.142857
e     0     8     1  0.000000

In [44]:
print(df)

   var1  var2  var3      var4
b     3     5     4  0.600000
c     2     7     1  0.285714
d     8     7     3  1.142857
e     0     8     1  0.000000

In [45]:
df.drop("var4", axis = 1, inplace = True)
df

   var1  var2  var3
b     3     5     4
c     2     7     1
d     8     7     3
e     0     8     1

In [47]:
l = ["var1","var2"]
df.drop(l,axis = 1)

   var3
b     4
c     1
d     3
e     1

## Gözlem ve Değişken Seçimi

In [49]:
m = np.random.randint(1,30,size = (10,3))
df = pd.DataFrame(m, columns= ["var1","var2","var3"])
df

   var1  var2  var3
0     2     4    25
1     6     8    22
2    18    13    25
3    29    16    26
4     9     9    12
5     9     3    29
6    16     2    16
7     2     9    15
8    26    15     7
9    25     4    15

### loc
- loc ile tanımladığı şekilde seçim yapmak için kullanılır.
- **Örnek:** x.iloc[3] deyince indekslenen 0,1,2,3 gelir(indeksten farklı olarak)

In [50]:
df.loc[0 : 3]

   var1  var2  var3
0     2     4    25
1     6     8    22
2    18    13    25
3    29    16    26

In [52]:
df.loc[0:0]

   var1  var2  var3
0     2     4    25

### iloc
- iloc ile alışık olduğumuz indeksleme mantığıyla seçim yapmak için kullanılır.
- **Örnek:** x.iloc[3] deyince indekslenen 0,1,2 gelir(indekste olduğu gibi)

In [51]:
df.iloc[0:0]

Empty DataFrame
Columns: [var1, var2, var3]
Index: []

In [53]:
df.iloc[0 :3]

   var1  var2  var3
0     2     4    25
1     6     8    22
2    18    13    25

In [54]:
df.iloc[:3,:2]

   var1  var2
0     2     4
1     6     8
2    18    13

In [55]:
df.iloc[:2,:3]

   var1  var2  var3
0     2     4    25
1     6     8    22

In [57]:
df.loc[0:3,"var3"]

0    25
1    22
2    25
3    26
Name: var3, dtype: int64

## Koşullu Eleman İşlemleri

In [59]:
df[df.var1 > 15]

   var1  var2  var3
2    18    13    25
3    29    16    26
6    16     2    16
8    26    15     7
9    25     4    15

In [60]:
df[df.var1 % 2 == 0]

   var1  var2  var3
0     2     4    25
1     6     8    22
2    18    13    25
6    16     2    16
7     2     9    15
8    26    15     7

In [61]:
df.loc[(df.var1 > 15) & (df.var3 < 15), "var2"]

8    15
Name: var2, dtype: int64

In [65]:
df.query("var1 > 15 & var3 < 15")

   var1  var2  var3
8    26    15     7

## Birleştirme (Join) İşlemleri

In [66]:
df2 = df + 99
df2

   var1  var2  var3
0   101   103   124
1   105   107   121
2   117   112   124
3   128   115   125
4   108   108   111
5   108   102   128
6   115   101   115
7   101   108   114
8   125   114   106
9   124   103   114

- `.concat()` fonksiyonu ile iki dataframe'i birleştirebiliriz. 
- ignore_index parametresi ile indexleri sıfırlaayabiliriz.
- join parametresi ile hangi kolon üzerinden birleştirileceğini belirleyebiliriz.

In [67]:
pd.concat([df,df2])

   var1  var2  var3
0     2     4    25
1     6     8    22
2    18    13    25
3    29    16    26
4     9     9    12
5     9     3    29
6    16     2    16
7     2     9    15
8    26    15     7
9    25     4    15
0   101   103   124
1   105   107   121
2   117   112   124
3   128   115   125
4   108   108   111
5   108   102   128
6   115   101   115
7   101   108   114
8   125   114   106
9   124   103   114

In [70]:
pd.concat([df,df2], ignore_index = True)

    var1  var2  var3
0      2     4    25
1      6     8    22
2     18    13    25
3     29    16    26
4      9     9    12
5      9     3    29
6     16     2    16
7      2     9    15
8     26    15     7
9     25     4    15
10   101   103   124
11   105   107   121
12   117   112   124
13   128   115   125
14   108   108   111
15   108   102   128
16   115   101   115
17   101   108   114
18   125   114   106
19   124   103   114

In [71]:
df2.columns = ["var1","var2","var3"]
pd.concat([df,df2], join = "inner")

   var1  var2  var3
0     2     4    25
1     6     8    22
2    18    13    25
3    29    16    26
4     9     9    12
5     9     3    29
6    16     2    16
7     2     9    15
8    26    15     7
9    25     4    15
0   101   103   124
1   105   107   121
2   117   112   124
3   128   115   125
4   108   108   111
5   108   102   128
6   115   101   115
7   101   108   114
8   125   114   106
9   124   103   114

## İleri Birleştirme İşlemleri

In [74]:
df1 = pd.DataFrame({"Çalışanlar" : ["Ahmet", "Emirhan", "Berkcan", "Eslem"],
                    "Grup" : ["Koordinatör", "Full Time Çalışan", "Eğitim Koordinatörü", "İş Geliştirme"]})

df1

  Çalışanlar                 Grup
0      Ahmet          Koordinatör
1    Emirhan    Full Time Çalışan
2    Berkcan  Eğitim Koordinatörü
3      Eslem        İş Geliştirme

In [75]:
df2 = pd.DataFrame({"Çalışanlar" : ["Ahmet", "Emirhan", "Berkcan", "Eslem"],
                    "İlk Giriş Yılı" : [2021, 2019, 2022, 2018]})
df2

  Çalışanlar  İlk Giriş Yılı
0      Ahmet            2021
1    Emirhan            2019
2    Berkcan            2022
3      Eslem            2018

### .merge()

- `.merge()` fonksiyonu ile birebir birleştirme işlemlerini gerçekleştirebiliriz.
- Merge komutu ile yapılan işlemleri SQL'de bulunan inner join, outer join ...'e benzetebiliriz.

In [76]:
pd.merge(df1,df2)

  Çalışanlar                 Grup  İlk Giriş Yılı
0      Ahmet          Koordinatör            2021
1    Emirhan    Full Time Çalışan            2019
2    Berkcan  Eğitim Koordinatörü            2022
3      Eslem        İş Geliştirme            2018

In [77]:
pd.merge(df1,df2,on = "Çalışanlar")

  Çalışanlar                 Grup  İlk Giriş Yılı
0      Ahmet          Koordinatör            2021
1    Emirhan    Full Time Çalışan            2019
2    Berkcan  Eğitim Koordinatörü            2022
3      Eslem        İş Geliştirme            2018

## Toplulaştırma ve Gruplama İşlemleri (Aggregation & Grouping)

### Basit Toplulaştırma İşlemleri
- count() : eleman sayısı
- first(), last() : ilk ve son eleman
- mean(), median() : ortalama, medyan
- min(), max() : minimum, maksimum değer
- std(), var() : Standart sapma, varyans
- sum() : topla değer

In [1]:
import seaborn as sns
df = sns.load_dataset("planets")
df.head()

            method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [8]:
df.shape

(1035, 6)

In [4]:
df.count()

method            1035
number            1035
orbital_period     992
mass               513
distance           808
year              1035
dtype: int64

In [11]:
df.mean

<bound method DataFrame.mean of                method  number  orbital_period   mass  distance  year
0     Radial Velocity       1      269.300000   7.10     77.40  2006
1     Radial Velocity       1      874.774000   2.21     56.95  2008
2     Radial Velocity       1      763.000000   2.60     19.84  2011
3     Radial Velocity       1      326.030000  19.40    110.62  2007
4     Radial Velocity       1      516.220000  10.50    119.47  2009
...               ...     ...             ...    ...       ...   ...
1030          Transit       1        3.941507    NaN    172.00  2006
1031          Transit       1        2.615864    NaN    148.00  2007
1032          Transit       1        3.191524    NaN    174.00  2007
1033          Transit       1        4.125083    NaN    293.00  2008
1034          Transit       1        4.187757    NaN    260.00  2008

[1035 rows x 6 columns]>

In [15]:
df["mass"].mean()

np.float64(2.6381605847953216)

In [16]:
df["mass"].count()

np.int64(513)

In [18]:
df["mass"].min()

np.float64(0.0036)

In [19]:
df["mass"].max()

np.float64(25.0)

In [23]:
df["mass"].sum()

np.float64(1353.37638)

In [21]:
df["mass"].std()

np.float64(3.8186166509616046)

In [24]:
df["mass"].var()

np.float64(14.58183312700122)

In [25]:
df.describe()

            number  orbital_period        mass     distance         year
count  1035.000000      992.000000  513.000000   808.000000  1035.000000
mean      1.785507     2002.917596    2.638161   264.069282  2009.070531
std       1.240976    26014.728304    3.818617   733.116493     3.972567
min       1.000000        0.090706    0.003600     1.350000  1989.000000
25%       1.000000        5.442540    0.229000    32.560000  2007.000000
50%       1.000000       39.979500    1.260000    55.250000  2010.000000
75%       2.000000      526.005000    3.040000   178.500000  2012.000000
max       7.000000   730000.000000   25.000000  8500.000000  2014.000000

In [26]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
number,1035.0,1.785507,1.240976,1.000000,1.00000,1.0000,2.000,7.0
orbital_period,992.0,2002.917596,26014.728304,0.090706,5.44254,39.9795,526.005,730000.0
mass,513.0,2.638161,3.818617,0.003600,0.22900,1.2600,3.040,25.0
distance,808.0,264.069282,733.116493,1.350000,32.56000,55.2500,178.500,8500.0
year,1035.0,2009.070531,3.972567,1989.000000,2007.00000,2010.0000,2012.000,2014.0

In [27]:
df.dropna().describe().T

,count,mean,std,min,25%,50%,75%,max
number,498.0,1.734940,1.175720,1.0000,1.00000,1.000,2.0000,6.0
orbital_period,498.0,835.778671,1469.128259,1.3283,38.27225,357.000,999.6000,17337.5
mass,498.0,2.509320,3.636274,0.0036,0.21250,1.245,2.8675,25.0
distance,498.0,52.068213,46.596041,1.3500,24.49750,39.940,59.3325,354.0
year,498.0,2007.377510,4.167284,1989.0000,2005.00000,2009.000,2011.0000,2014.0